### ISSUE TITLE
Are these elements? 

### ISSUE THREAD

**Issue by username1290** [nagoli/figma-spacers#1]
Question:
Are these additional elements that one adds to Figma?
and when you turn it off, what happens?

also, is there a screencapture or GIF of the tool being used?

**Comment by nagoli** [comment]
Hi yes there are elements in the layout.
They can be hidden or not but are not removed
you can see the plugin page on figma : https://www.figma.com/community/plugin/802230205741773645/Spacers

thanks for your feedback

**Comment by username1290** [comment]
thanks!
