### ISSUE TITLE
Positioning controls (left/right/top/bottom)

### ISSUE THREAD

**Issue by AlexisRiols** [nagoli/figma-spacers#2]
Hello

J'utilise votre plugin sur figma qui est super cool
Je fais le même hack manuellement pour contrôler l'autolayout 😉

Ajouter le contrôle de la position d'ajout des marges (pas uniquement en bottom) serait un luxe 🙏
<img width="171" alt="Capture d’écran 2020-03-16 à 23 17 13" src="https://user-images.githubusercontent.com/17720347/76804374-597c3600-67dc-11ea-9f98-426364c58acd.png">

**Comment by nagoli** [comment]
bonjour
 bonne idée merci je vais m’en occuper

**Comment by nagoli** [comment]
c est fait 
merci pour l’idée
